replicas: 2

image:
  repository: ghcr.io/datapunchorg/remoteshuffleservice
  tag: k8s-spark-3.2

resources:
  requests:
    memory: "1G"
    cpu: "500m"
  limits:
    memory: "1G"
    cpu: "500m"

command:
  jvmHeapSizeOption: "-Xmx800M"

ports:
  shuffleServer: 9338
  healthcheck: 8080
