# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Manually release client

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      name:
        description: 'Release Name'
        required: true
        default: '0.0.0'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2

    - name: Install gpg secret key
      run: |
        cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
        gpg --list-secret-keys --keyid-format LONG

# https://central.sonatype.org/publish/publish-maven/
# https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven
# https://s01.oss.sonatype.org
    - name: Set up JDK and Maven Central Repository
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD

    - name: Build and publish client jar files to Maven repository
      run: mvn --batch-mode clean deploy -Pclient -DskipTests --file pom.xml -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

