# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Manually release

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      name:
        description: 'Release Name'
        required: true
        default: '0.0.0'
        
jobs:
  build:

    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build and publish client jar files to Maven repository
      run: mvn --batch-mode deploy -Pclient -DskipTests --file pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and publish server jar files to Maven repository
      run: |
        mvn --batch-mode deploy -Pserver -DskipTests --file pom.xml
        mkdir -p target/server-jar-file
        cp `ls target/*.jar | grep -v sources.jar | grep -v original` target/server-jar-file/
        echo Files inside target/server-jar-file/
        ls -l target/server-jar-file/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
