# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Manually release

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Release Name'
        required: true
        default: '0.0.0'
        
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn -B package -Pclient -DskipTests --file pom.xml
